version: '2'

services:
  web:
    image: chriha/web:php7.1-latest
    volumes:
      - ./src:/var/www
    ports:
      - "${APP_PORT}:80"
    networks:
      - def_network
    links:
      - db
      - redis
      - rabbit
    env_file:
      - ./src/.env
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - def_network
  node:
    image: chriha/node:7.2-latest
    volumes:
      - ./src:/var/www
    networks:
      - def_network
  yarn:
    image: kkarczmarczyk/node-yarn
    volumes:
      - ./src:/var/www
    networks:
      - def_network
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    networks:
      - def_network
    command: redis-server --requirepass "${REDIS_PASS}"
  rabbit:
    image: rabbitmq:3.6-management
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq@rabbit
    networks:
      - def_network
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    ports:
      - "15672:15672"
  mailcatcher:
    image: chriha/mailcatcher:0.6-latest
    networks:
      - def_network
    ports:
      - "1080:1080"

networks:
  def_network:
    driver: "bridge"

