version: '2'

services:
  web:
    build:
      context: ./systems/web
      dockerfile: Dockerfile
    image: chriha/web
    volumes:
      - ./src:/var/www
    ports:
      - "${APP_PORT}:80"
    networks:
      - def_network
    links:
      - db
      - redis
      - rabbit
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - def_network
  node:
    build:
      context: ./systems/node
      dockerfile: Dockerfile
    image: chriha/node
    volumes:
      - ./src:/var/www
    networks:
      - def_network
  yarn:
    image: kkarczmarczyk/node-yarn
    volumes:
      - ./src:/var/www
    networks:
      - def_network
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    networks:
      - def_network
  rabbit:
    image: rabbitmq:3.6-management
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq@rabbit
    networks:
      - def_network
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    ports:
      - "15672:15672"

networks:
  def_network:
    driver: "bridge"

